### ISSUE TITLE
Any chance of an update for Quantum?

### ISSUE THREAD

**Issue by Samizdata** [astral-sa/salr#130]
Or does the new architecture preclude that working?

Or does no one care anymore?

I REALLY miss my edit window...

**Comment by astral-sa** [comment]
The direction things are going is porting the chrome extension over to Firefox. Follow the new SALR Redux thread for the latest: https://forums.somethingawful.com/showthread.php?threadid=3845597

Sometime in the next couple of months, I intend to write some migration logic so user notes and any relevant thread info from the legacy SALR will get imported for those still using Firefox ESR.

**Comment by Samizdata** [comment]
Cheers.  Too many threads to track them all.
